### ISSUE TITLE
HowTo: interject intermittent entropy?

### ISSUE THREAD

**Issue by d3x0r** [imneme/pcg-c#22]
Not an issue per-se; just a usage query.
My existing RNG is based on grabbing bits from a SHA2 stream.  It passes tests very well; but it is computationally expensive.  However, as a by-product of doing it this way, when I need another 512 bits of entropy, I call a callback that adds data to the sequence; if nothing additional is added it uses the previous output as the input, if additional data is provided, the previous output plus the additional data is used as the input the SHA2 generator...
https://github.com/d3x0r/-/blob/master/org.d3x0r.common/salty_random_generator.js#L3

Other than the initial seed, I would like to retain that sort of ability... I was planning on using a RNG something like this instead, grabbing 4 or 8  128 bit values at a time... (maybe a configurable length) and then having the ability to modify the seed...

-- 
Edit: I do plan on using this for procedural generators; (like perlin noise) so reproducability is key;  Also for building sectors of voxels using 3d perlin noise to describee like ore content; so I can use the x,y,z of the sector as a seed for the noise generated for that sector...

**Comment by Ivoz** [comment]
xor bits into the the state bytes?

If your implementation is in complete js and you're wondering about speed, most modern js engines now have very good normal PRNG (xorshift128+) that you might be able to get two instances of and combine, unless the JIT'ed js manages to be just as fast...

**Comment by d3x0r** [comment]
C and JS run the SHA2 about the same speed... it's just an intense algorithm...
and the standard library functions only allow me one stream of randomness; can't fork it with additional information...

**Comment by d3x0r** [comment]
https://gist.github.com/d3x0r/345b256be6569c0086c328a8d1b4be01
got some of it roughly ported to JS....
can switch between 16,32,64,128 bit ... uses arrays of half dwords; tried initially with UInt32Array but that was sub-optimal.
32 bit Runs 37 times faster than sha2(also in JS)  (10M in 419ms or 23,866/ms)
128 bit runs 16 times faster than sha2(also in JS)  (10M in 943ms or 10,604/ms)

sha2 is running (1M in 1594ms or 627/ms)  actually that's for only 4 character input hash
something closer to what I uusually use is like (1M in 5688ms or 175/ms (which makes 128bit JS PCG 60 times faster)

**Comment by d3x0r** [comment]
Ya, this is bad for generating a stream of bits... not really sure but 70% of the time the value is 0; and it's not a bounded return; basically I'm returning the low 2 shorts concated...   in 10M bits from sha2 it's within +/- 8200  or like 0.082% deviation; and turns out all the other process is heavier than I though.
